name: greensheart_app
description: A new Flutter project.
publish_to: "none"

version: 1.7.1+1

environment:
  sdk: ">=3.7.0 <4.0.0"  # Updated to be compatible with SystemPulse

dependencies:
  # SystemPulse Integration - FIXED
  system_pulse_monitor:
    git:
      url: https://github.com/GrindingHZ/systemfulse.git
      path: system_pulse_package
      
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.2
  fluro: ^2.0.5
  mobx: ^2.2.0
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0
  get_it: ^8.0.3
  info_popup: ^4.3.1
  flutter_mobx: ^2.1.0
  objectbox: ^4.0.0
  objectbox_flutter_libs: ^4.0.0
  shared_preferences: ^2.3.4
  intl: ^0.19.0
  auto_size_text: ^3.0.0
  http: ^1.4.0
  health: ^12.0.1
  flutter_activity_recognition: ^4.0.0
  battery_plus: ^6.0.1
  envied: ^1.0.0
  openid_client: ^0.4.8
  url_launcher: ^6.2.5
  flutter_secure_storage: ^9.2.1
  background_fetch: ^1.3.2
  flutter_background_geolocation: ^4.16.9
  permission_handler: ^11.3.1
  app_settings: ^5.1.1
  sensors_plus: ^6.1.1
  device_info_plus: ^11.3.3
  graphql_flutter: ^5.1.2
  internet_connection_checker: ^3.0.1
  dartz: ^0.10.1
  uuid: ^4.4.0
  path_provider: ^2.1.3
  share_plus: ^10.0.2
  firebase_core: ^3.6.0
  image_picker: ^1.1.1
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  table_calendar: ^3.0.9
  fl_chart: ^0.70.2
  open_settings_plus: ^0.4.0
  external_app_launcher: ^4.0.3
  firebase_messaging: ^15.1.3
  flutter_blue_plus: ^1.32.12
  flutter_inappwebview: ^6.1.5
  device_preview: ^1.2.0
  light: ^4.1.0
  flutter_native_splash: ^2.4.4
  youtube_player_flutter: ^9.1.1
  file_picker: ^10.1.7
  confetti: ^0.8.0
  syncfusion_flutter_charts: ^28.2.11
  collection: ^1.18.0
  audioplayers: ^6.1.0
  firebase_crashlytics: ^4.3.1
  firebase_analytics: ^11.4.1
  timezone: ^0.10.0
  flutter_timezone: ^4.0.0
  package_info_plus: ^8.2.1
  source_gen: ^1.5.0
  analyzer: ^6.7.0
  build: ^2.4.1
  glob: ^2.1.3
  path: ^1.9.0
  dart_style: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  objectbox_generator: ^4.0.0
  envied_generator: ^1.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - lib/assets/

  fonts:
    - family: Overpass
      fonts:
        - asset: fonts\Overpass-VariableFont_wght.ttf
