pluginManagement {
    /**
     * Locates the Flutter SDK.
     *
     * `local.properties` is generated by the Flutter tool and is git-ignored, so it does not exist
     * on a fresh checkout. Requiring it meant `./gradlew` could not be invoked directly in CI —
     * or by a contributor who had not yet run a Flutter build — and failed with a bare
     * "local.properties (No such file or directory)".
     *
     * The file is still preferred when present. Otherwise FLUTTER_ROOT is used, which the Flutter
     * tool exports and which setup actions set.
     */
    val flutterSdkPath = run {
        val propertiesFile = file("local.properties")
        val fromProperties = if (propertiesFile.exists()) {
            java.util.Properties()
                .apply { propertiesFile.inputStream().use { load(it) } }
                .getProperty("flutter.sdk")
        } else {
            null
        }

        val path = fromProperties ?: System.getenv("FLUTTER_ROOT")
        require(!path.isNullOrBlank()) {
            "Flutter SDK not found. Set flutter.sdk in android/local.properties (running any " +
                "flutter command in the project root generates it), or set FLUTTER_ROOT."
        }
        path
    }

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

/*
 * Version floors are enforced by Flutter's DependencyVersionChecker, which fails the build below
 * Gradle 8.14.0, AGP 8.11.1 and Kotlin 2.2.20 for this SDK. The versions here are the lowest that
 * clear all three.
 *
 * Flutter's own template targets Gradle 9.3.1 / AGP 9.1.0 / Kotlin 2.4.0, which would also silence
 * the checker's (non-fatal) "consider upgrading" warnings. That jump is deliberately not taken
 * here: AGP 9 is a major release that removes DSL this build file still uses, and it is not a
 * change to make blind. Upgrading is a worthwhile follow-up on a machine that can run the build.
 */
plugins {
    id("dev.flutter.flutter-plugin-loader") version "1.0.0"
    id("com.android.application") version "8.11.1" apply false
    id("org.jetbrains.kotlin.android") version "2.2.20" apply false
}

include(":app")
