pluginManagement {
    /**
     * Locates the Flutter SDK.
     *
     * `local.properties` is generated by the Flutter tool and is git-ignored, so it does not exist
     * on a fresh checkout. Requiring it meant `./gradlew` could not be invoked directly in CI —
     * or by a contributor who had not yet run a Flutter build — and failed with a bare
     * "local.properties (No such file or directory)".
     *
     * The file is still preferred when present. Otherwise FLUTTER_ROOT is used, which the Flutter
     * tool exports and which setup actions set.
     */
    val flutterSdkPath = run {
        val propertiesFile = file("local.properties")
        val fromProperties = if (propertiesFile.exists()) {
            java.util.Properties()
                .apply { propertiesFile.inputStream().use { load(it) } }
                .getProperty("flutter.sdk")
        } else {
            null
        }

        val path = fromProperties ?: System.getenv("FLUTTER_ROOT")
        require(!path.isNullOrBlank()) {
            "Flutter SDK not found. Set flutter.sdk in android/local.properties (running any " +
                "flutter command in the project root generates it), or set FLUTTER_ROOT."
        }
        path
    }

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("dev.flutter.flutter-plugin-loader") version "1.0.0"
    id("com.android.application") version "8.7.3" apply false
    id("org.jetbrains.kotlin.android") version "2.1.0" apply false
}

include(":app")
